language: node_js
node_js:
    - 6
    - 5
    - 4
addons:
  code_climate:
    repo_token: fa1944104bfdc21eb82dd5469c295d41aea34f74646339f8eaac4716caa84466

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info
